# Site settings
title: Nadiia's space
description: To find out
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Nadiia Duiuinova
user_description: An aspiring data scientist.
user_title: Data Scientist
email: nadiia.duiuinova@gmail.com
cv: my-github-cv-bucket.s3.eu-west-1.amazonaws.com/cv.pdf
# twitter_username: lorem_ipsum
#instagram_username: mauriciourraco7
#facebook_username: mauricio.urraco
linkedin_username: nadiia-duiunova
github_username:  nadiia95
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

